create sequence kategorie_osiagniec_seq start with 1 increment by 50;
create sequence kryteria_oceny_seq start with 1 increment by 50;
create sequence oceny_seq start with 1 increment by 50;
create sequence okres_rozliczeniowy_seq start with 1 increment by 50;
create sequence osiagniecia_seq start with 1 increment by 50;
create sequence pod_kategorie_seq start with 1 increment by 50;
create sequence pracownicy_seq start with 1 increment by 50;
create sequence pracownik_stanowiska_seq start with 1 increment by 50;
create sequence rodzaje_dzialalnosci_seq start with 1 increment by 50;
create sequence role_seq start with 1 increment by 50;
create sequence stopnie_naukowe_seq start with 1 increment by 50;
create sequence wnioski_seq start with 1 increment by 50;
create table kategorie_osiagniec (id_kategoria_osiagniec bigint not null, nazwa_kategorii varchar(255), primary key (id_kategoria_osiagniec));
create table kryteria_oceny (czy_na_stanowisku_kierowniczym boolean, czy_posiada_stopien_naukowy boolean, prog_ocenyzwyroznieniemdo integer, prog_ocenyzwyroznieniemnb integer, prog_pozytywnej_ocenydo integer, prog_pozytywnej_ocenynb integer, id_kryterium bigint not null, primary key (id_kryterium));
create table oceny (ilosc_punktow integer, data timestamp(6), id_oceny bigint not null, id_pracownika bigint, id_wniosku bigint, wniosek_id_wniosku bigint, nazwa varchar(255), primary key (id_oceny));
create table okres_rozliczeniowy (id_okresu bigint not null, koniec timestamp(6), poczatek timestamp(6), primary key (id_okresu));
create table osiagniecia (czy_zatwierdzone boolean, ilosc_punktow integer, data timestamp(6), id_osiagniecia bigint not null, id_pod_kategorii bigint, id_pracownika bigint, id_wniosku bigint, nazwa varchar(255), primary key (id_osiagniecia));
create table pod_kategorie (max_punktow integer, min_punktow integer, id_kategorii bigint, id_pod_kategorii bigint not null, nazwa varchar(255), primary key (id_pod_kategorii));
create table pracownicy (id_pracownika bigint not null, id_rodzaj_dzialalnosci bigint, id_roli bigint, id_stanowiska bigint, id_stopnia_naukowego bigint, email varchar(255), imie varchar(255), nazwisko varchar(255), primary key (id_pracownika));
create table pracownik_stanowiska (id_stanowiska bigint not null, nazwa varchar(255), primary key (id_stanowiska));
create table rodzaje_dzialalnosci (id_rodzaj_dzialalnosci bigint not null, nazwa varchar(255), primary key (id_rodzaj_dzialalnosci));
create table role (id_roli bigint not null, nazwa varchar(255), primary key (id_roli));
create table stopnie_naukowe (id_stopnia_naukowego bigint not null, nazwa varchar(255), primary key (id_stopnia_naukowego));
create table wnioski (id_okresu bigint, id_pracownika bigint, id_wniosku bigint not null, primary key (id_wniosku));
